import { glob } from 'astro/loaders';
import { defineCollection } from 'astro:content';
import { ArticleSchema, HindiArticleSchema, HindiPartSchema, PartSchema, ScheduleSchema } from './lib/schemas/index.ts';

/**
 * Collection entries under src/content/<name>/ are generated by
 * `npm run data:sync` from data/processed/constitution.json (and
 * constitution-hindi.json for the -hi collections) and are not committed.
 * The schemas are the same ones the extraction pipeline validates against,
 * so collections cannot drift from the source data.
 */
const articles = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/articles' }),
  schema: ArticleSchema,
});

const parts = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/parts' }),
  schema: PartSchema,
});

const schedules = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/schedules' }),
  schema: ScheduleSchema,
});

const articlesHi = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/articles-hi' }),
  schema: HindiArticleSchema,
});

const partsHi = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/parts-hi' }),
  schema: HindiPartSchema,
});

export const collections = { articles, parts, schedules, articlesHi, partsHi };
