import { glob } from 'astro/loaders';
import { defineCollection } from 'astro:content';
import { ArticleSchema, PartSchema, ScheduleSchema } from './lib/schemas/index.ts';

/**
 * Collection entries under src/content/<name>/ are generated by
 * `npm run data:sync` from data/processed/constitution.json and are not
 * committed. The schemas are the same ones the extraction pipeline
 * validates against, so collections cannot drift from the source data.
 */
const articles = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/articles' }),
  schema: ArticleSchema,
});

const parts = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/parts' }),
  schema: PartSchema,
});

const schedules = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/schedules' }),
  schema: ScheduleSchema,
});

export const collections = { articles, parts, schedules };
